# Normalização de Itens de Notas Fiscais com LLMs

## Pipeline

1. **Setup** — instalar dependências e configurar API
2. **Carregar dados** — dataset com variações não normalizadas
3. **Definir few-shot examples** — 1 exemplo por produto como guia
4. **Montar o prompt** — estrutura inspirada no WDC-PAVE (6 blocos), batch de 10 itens
5. **Chamar a API do Gemini** — normalizar em lotes + medir tempo e custo
6. **Avaliar resultados** — Exact Match, WER e F1-score
7. **Análise de erros** — entender onde o modelo errou

---
## 1. Setup

In [ ]:
!pip install google-genai jiwer -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 33.3 MB/s eta 0:00:00

In [ ]:
from google import genai
import pandas as pd
import json
import time
from jiwer import wer

GOOGLE_API_KEY = "AIzaSyBUZlRHSZnezf7dzpruGu9nNVekmpLHV30"

client = genai.Client(api_key=GOOGLE_API_KEY)
MODEL_ID = "gemini-3.1-flash-lite-preview"

PRECO_INPUT_POR_MILHAO  = 0.25
PRECO_OUTPUT_POR_MILHAO = 1.50

print("--- API configurada com sucesso")
print(f"--- Modelo: {MODEL_ID}")

API configurada com sucesso!
   Modelo: gemini-3.1-flash-lite-preview

---
## 2. Carregar Dados

In [ ]:
df = pd.read_csv('/content/itens_nf_normalizacao_v3.csv')

# Cada grupo de 10 linhas consecutivas corresponde ao mesmo produto
# A coluna 'produto_id' identifica o grupo
df['produto_id'] = df.index // 10

print(f"Total de itens no dataset: {len(df)}")
print(f"Produtos únicos: {df['produto_id'].nunique()}")
print(f"Colunas: {list(df.columns)}")
print()
df.head(10)

Total de itens no dataset: 190
Produtos únicos: 19
Colunas: ['item_nao_normalizado', 'item_normalizado', 'produto_id']

    item_nao_normalizado    item_normalizado  produto_id
0                  CC 2L  Coca-Cola 2 Litros           0
1         COCA COLA 2 LT  Coca-Cola 2 Litros           0
2           COKA COLA 2L  Coca-Cola 2 Litros           0
3          COCA-COLA 2LT  Coca-Cola 2 Litros           0
4      COCACOLA 2 LITROS  Coca-Cola 2 Litros           0
5            CCA COLA 2L  Coca-Cola 2 Litros           0
6         REFRIG COCA 2L  Coca-Cola 2 Litros           0
7  COCA COLA DOIS LITROS  Coca-Cola 2 Litros           0
8          REFRIG CC 2LT  Coca-Cola 2 Litros           0
9       COCA COLA 2000ML  Coca-Cola 2 Litros           0

---
## 3. Definir Gabarito e Few-Shot Examples

Para cada produto:
- **1 exemplo few-shot** (1ª linha do grupo) → usado no prompt para ensinar o modelo
- **Restante** (9 linhas) → dataset de teste para avaliar

O gabarito é a coluna `item_normalizado` do próprio dataset.

In [ ]:
# Separar few-shot (1ª linha de cada produto) e teste (restante)
df_few_shot = df.groupby('produto_id').head(1).copy()
df_test = df.groupby('produto_id').apply(lambda x: x.iloc[1:]).reset_index(drop=True)

# Gabarito: mapeamento item_nao_normalizado -> item_normalizado para todo o dataset
gabarito = dict(zip(df['item_nao_normalizado'], df['item_normalizado']))

# Gabarito por produto_id (forma canônica)
gabarito_por_produto = df.groupby('produto_id')['item_normalizado'].first().to_dict()

print(f"Few-shot examples: {len(df_few_shot)} (1 por produto)")
print(f"Dataset de teste:  {len(df_test)} itens")
print()
print("Exemplos few-shot (entrada → saída esperada):")
for _, row in df_few_shot.iterrows():
    print(f"  ENTRADA: {row['item_nao_normalizado']}")
    print(f"  SAÍDA:   {row['item_normalizado']}")
    print()

Few-shot examples: 19 (1 por produto)
Dataset de teste:  171 itens

Exemplos few-shot (entrada → saída esperada):
  ENTRADA: CC 2L
  SAÍDA:   Coca-Cola 2 Litros

  ENTRADA: CADEADO PADO LT-50MM
  SAÍDA:   Cadeado Pado LT-50MM

  ENTRADA: ARR BCO TJ 1KG
  SAÍDA:   Arroz Branco Tio João 1 Kg

  ENTRADA: FEJ CARIOCA KICALDO 1KG
  SAÍDA:   Feijão Carioca Kicaldo 1 Kg

  ENTRADA: LEITE INTEGRAL ITALAC 1L
  SAÍDA:   Leite Integral Italac 1 Litro

  ENTRADA: ACU CRISTAL UNIAO 1KG
  SAÍDA:   Açúcar Cristal União 1 Kg

  ENTRADA: CAFE PILO TRAD 500G
  SAÍDA:   Café Tradicional Pilão 500 g

  ENTRADA: DET LIMAO YPE 500ML
  SAÍDA:   Detergente Limão Ypê 500 ml

  ENTRADA: SAB PO OMO LAVANDA 1KG
  SAÍDA:   Sabão em Pó OMO Lavanda 1 Kg

  ENTRADA: AGUA MIN SG CRYSTAL 500ML
  SAÍDA:   Água Mineral Sem Gás Crystal 500 ml

  ENTRADA: BISCOITO CREAM CRACKER BAUDUCCO 200G
  SAÍDA:   Biscoito Cream Cracker Bauducco 200 g

  ENTRADA: MACARRAO ESPAGUETE ADRIA 500G
  SAÍDA:   Macarrão Espaguete Adria 500 g

  ENTRADA: AZEITE EXT VIRGEM GALO 500ML
  SAÍDA:   Azeite Extra Virgem Galo 500 ml

  ENTRADA: SHAMP ANTICASPA HEAD SHOULDERS 200ML
  SAÍDA:   Shampoo Anticaspa Head & Shoulders 200 ml

  ENTRADA: CREME DENTAL MENTA COLGATE 90G
  SAÍDA:   Creme Dental Menta Colgate 90 g

  ENTRADA: FRALDA PAMPERS SUPERSEC M C/30
  SAÍDA:   Fralda Pampers Supersec Tamanho M 30 Unidades

  ENTRADA: CERVEJA SKOL PURO MALTE 269ML LT
  SAÍDA:   Cerveja Skol Puro Malte 269 ml Lata

  ENTRADA: PNEU 175/70R13 BRIDGESTONE
  SAÍDA:   Pneu 175/70 R13 Bridgestone

  ENTRADA: OLEO MOTOR 5W30 SINT CASTROL 1L
  SAÍDA:   Óleo de Motor Sintético 5W30 Castrol 1 Litro

/tmp/ipykernel_3423/798066882.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_test = df.groupby('produto_id').apply(lambda x: x.iloc[1:]).reset_index(drop=True)

---
## 4. Montar o Prompt (Batch de 10 itens)

Estrutura baseada no **WDC-PAVE** (Brinkmann et al., 2024) com 6 blocos:
1. Role description
2. Task description  
3. Few-shot examples
4. Demonstrações
5. Task input (lote de itens)
6. Task output (JSON array)

In [ ]:
def montar_few_shot_str(df_few_shot):
    """Monta a string com todos os exemplos few-shot."""
    exemplos = []
    for _, row in df_few_shot.iterrows():
        entrada = row['item_nao_normalizado']
        saida   = row['item_normalizado']
        exemplos.append(f'  Entrada: "{entrada}"\n  Saída:   "{saida}"')
    return "\n\n".join(exemplos)


def montar_prompt_batch(itens_batch, df_few_shot):
    """
    Monta o prompt para um lote de itens (lista de strings).

    Retorna o prompt completo seguindo a estrutura WDC-PAVE.
    Saída esperada: JSON array com um objeto por item.
    """
    few_shot_str = montar_few_shot_str(df_few_shot)

    # Monta lista numerada dos itens do lote
    itens_str = "\n".join([f'  {i+1}. "{item}"' for i, item in enumerate(itens_batch)])

    prompt = f"""[ROLE]
Você é um sistema especializado em normalização de descrições de produtos de notas fiscais brasileiras.
Seu objetivo é padronizar descrições sujas/abreviadas para um formato legível e consistente.

[TASK]
Normalize cada descrição de produto seguindo estas regras:
- Expanda abreviações comuns (ex: "LT" → "Litros", "KG" → "Kg", "ML" → "ml", "G" → "g")
- Corrija erros de digitação e variações ortográficas
- Mantenha a estrutura: Nome → Marca → Modelo/Cor/Sabor → Peso/Volume/Tamanho
- Preserve nomes de marcas corretamente (ex: "PADO" é uma marca, não abreviação de "Padrão")
- Use capitalização Title Case (primeira letra maiúscula em cada palavra relevante)
- Não invente informações que não estão na descrição original
- Retorne APENAS um JSON array com exatamente {len(itens_batch)} objetos no formato:
  [{{"descricao_normalizada": "..."}}, ...]

[EXEMPLOS]
{few_shot_str}

[INPUT]
Normalize os {len(itens_batch)} itens abaixo:
{itens_str}

[OUTPUT]
"""
    return prompt


# Testar o prompt com o primeiro lote
exemplo_batch = df_test['item_nao_normalizado'].head(10).tolist()
prompt_teste = montar_prompt_batch(exemplo_batch, df_few_shot)
print("=== PROMPT DE EXEMPLO ===")
print(prompt_teste[:3000], "...")

=== PROMPT DE EXEMPLO ===
[ROLE]
Você é um sistema especializado em normalização de descrições de produtos de notas fiscais brasileiras.
Seu objetivo é padronizar descrições sujas/abreviadas para um formato legível e consistente.

[TASK]
Normalize cada descrição de produto seguindo estas regras:
- Expanda abreviações comuns (ex: "LT" → "Litros", "KG" → "Kg", "ML" → "ml", "G" → "g")
- Corrija erros de digitação e variações ortográficas
- Mantenha a estrutura: Nome → Marca → Modelo/Cor/Sabor → Peso/Volume/Tamanho
- Preserve nomes de marcas corretamente (ex: "PADO" é uma marca, não abreviação de "Padrão")
- Use capitalização Title Case (primeira letra maiúscula em cada palavra relevante)
- Não invente informações que não estão na descrição original
- Retorne APENAS um JSON array com exatamente 10 objetos no formato:
  [{"descricao_normalizada": "..."}, ...]

[EXEMPLOS]
  Entrada: "CC 2L"
  Saída:   "Coca-Cola 2 Litros"

  Entrada: "CADEADO PADO LT-50MM"
  Saída:   "Cadeado Pado LT-50MM"

  Entrada: "ARR BCO TJ 1KG"
  Saída:   "Arroz Branco Tio João 1 Kg"

  Entrada: "FEJ CARIOCA KICALDO 1KG"
  Saída:   "Feijão Carioca Kicaldo 1 Kg"

  Entrada: "LEITE INTEGRAL ITALAC 1L"
  Saída:   "Leite Integral Italac 1 Litro"

  Entrada: "ACU CRISTAL UNIAO 1KG"
  Saída:   "Açúcar Cristal União 1 Kg"

  Entrada: "CAFE PILO TRAD 500G"
  Saída:   "Café Tradicional Pilão 500 g"

  Entrada: "DET LIMAO YPE 500ML"
  Saída:   "Detergente Limão Ypê 500 ml"

  Entrada: "SAB PO OMO LAVANDA 1KG"
  Saída:   "Sabão em Pó OMO Lavanda 1 Kg"

  Entrada: "AGUA MIN SG CRYSTAL 500ML"
  Saída:   "Água Mineral Sem Gás Crystal 500 ml"

  Entrada: "BISCOITO CREAM CRACKER BAUDUCCO 200G"
  Saída:   "Biscoito Cream Cracker Bauducco 200 g"

  Entrada: "MACARRAO ESPAGUETE ADRIA 500G"
  Saída:   "Macarrão Espaguete Adria 500 g"

  Entrada: "AZEITE EXT VIRGEM GALO 500ML"
  Saída:   "Azeite Extra Virgem Galo 500 ml"

  Entrada: "SHAMP ANTICASPA HEAD SHOULDERS 200ML"
  Saída:   "Shampoo Anticaspa Head & Shoulders 200 ml"

  Entrada: "CREME DENTAL MENTA COLGATE 90G"
  Saída:   "Creme Dental Menta Colgate 90 g"

  Entrada: "FRALDA PAMPERS SUPERSEC M C/30"
  Saída:   "Fralda Pampers Supersec Tamanho M 30 Unidades"

  Entrada: "CERVEJA SKOL PURO MALTE 269ML LT"
  Saída:   "Cerveja Skol Puro Malte 269 ml Lata"

  Entrada: "PNEU 175/70R13 BRIDGESTONE"
  Saída:   "Pneu 175/70 R13 Bridgestone"

  Entrada: "OLEO MOTOR 5W30 SINT CASTROL 1L"
  Saída:   "Óleo de Motor Sintético 5W30 Castrol 1 Litro"

[INPUT]
Normalize os 10 itens abaixo:
  1. "COCA COLA 2 LT"
  2. "COKA COLA 2L"
  3. "COCA-COLA 2LT"
  4. "COCACOLA 2 LITROS"
  5. "CCA COLA 2L"
  6. "REFRIG COCA 2L"
  7. "COCA COLA DOIS LITROS"
  8. "REFRIG CC 2LT"
  9. "COCA COLA 2000ML"
  10. "CAD PDO LT50"

[OUTPUT]
 ...

---
## 5. Chamar a API do Gemini (Batch + Timer + Custo)

In [ ]:
# Contadores globais de tokens
total_tokens_input  = 0
total_tokens_output = 0


def normalizar_batch(itens_batch, df_few_shot, tentativas=3):
    """
    Chama a API do Gemini para normalizar um lote de itens.
    Retorna lista de strings normalizadas na mesma ordem do input.
    Em caso de falha total, retorna lista de 'ERRO'.
    """
    global total_tokens_input, total_tokens_output

    prompt = montar_prompt_batch(itens_batch, df_few_shot)

    for tentativa in range(tentativas):
        try:
            response = client.models.generate_content(
                model=MODEL_ID,
                contents=prompt
            )

            # Acumular tokens
            if hasattr(response, 'usage_metadata') and response.usage_metadata:
                total_tokens_input  += response.usage_metadata.prompt_token_count or 0
                total_tokens_output += response.usage_metadata.candidates_token_count or 0

            texto = response.text.strip()
            texto = texto.replace("```json", "").replace("```", "").strip()

            resultado = json.loads(texto)

            # Garantir que retornou a quantidade certa de itens
            normalizados = [r.get("descricao_normalizada", "") for r in resultado]
            if len(normalizados) == len(itens_batch):
                return normalizados
            else:
                print(f"  Aviso: retornou {len(normalizados)} itens, esperado {len(itens_batch)}. Tentando novamente...")

        except json.JSONDecodeError as e:
            print(f"  Tentativa {tentativa+1} — JSON inválido: {e}")
            time.sleep(2)
        except Exception as e:
            print(f"  Tentativa {tentativa+1} — Erro: {e}")
            time.sleep(2)

    return ["ERRO"] * len(itens_batch)


# Teste rápido com 1 lote antes de rodar tudo
print("=== TESTE COM 1 LOTE DE 10 ITENS ===")
batch_teste = df_test['item_nao_normalizado'].head(10).tolist()
resultados_teste = normalizar_batch(batch_teste, df_few_shot)
for entrada, saida in zip(batch_teste, resultados_teste):
    esperado = gabarito.get(entrada, 'N/A')
    print(f"  Entrada:  {entrada}")
    print(f"  Resultado:{saida}")
    print(f"  Gabarito: {esperado}")
    print()

=== TESTE COM 1 LOTE DE 10 ITENS ===
  Entrada:  COCA COLA 2 LT
  Resultado:Coca-Cola 2 Litros
  Gabarito: Coca-Cola 2 Litros

  Entrada:  COKA COLA 2L
  Resultado:Coca-Cola 2 Litros
  Gabarito: Coca-Cola 2 Litros

  Entrada:  COCA-COLA 2LT
  Resultado:Coca-Cola 2 Litros
  Gabarito: Coca-Cola 2 Litros

  Entrada:  COCACOLA 2 LITROS
  Resultado:Coca-Cola 2 Litros
  Gabarito: Coca-Cola 2 Litros

  Entrada:  CCA COLA 2L
  Resultado:Coca-Cola 2 Litros
  Gabarito: Coca-Cola 2 Litros

  Entrada:  REFRIG COCA 2L
  Resultado:Refrigerante Coca-Cola 2 Litros
  Gabarito: Coca-Cola 2 Litros

  Entrada:  COCA COLA DOIS LITROS
  Resultado:Coca-Cola 2 Litros
  Gabarito: Coca-Cola 2 Litros

  Entrada:  REFRIG CC 2LT
  Resultado:Refrigerante Coca-Cola 2 Litros
  Gabarito: Coca-Cola 2 Litros

  Entrada:  COCA COLA 2000ML
  Resultado:Coca-Cola 2 Litros
  Gabarito: Coca-Cola 2 Litros

  Entrada:  CAD PDO LT50
  Resultado:Cadeado Pado LT-50
  Gabarito: Cadeado Pado LT-50MM

In [ ]:
BATCH_SIZE = 10

resultados = []
itens_test = df_test['item_nao_normalizado'].tolist()
total_itens = len(itens_test)
total_batches = (total_itens + BATCH_SIZE - 1) // BATCH_SIZE

# Zerar contadores antes do loop principal
total_tokens_input  = 0
total_tokens_output = 0
tempo_inicio = time.time()

print(f"Iniciando normalização de {total_itens} itens em {total_batches} lotes de {BATCH_SIZE}...")
print()

for i in range(0, total_itens, BATCH_SIZE):
    batch_num   = i // BATCH_SIZE + 1
    batch_items = itens_test[i:i + BATCH_SIZE]

    normalizados = normalizar_batch(batch_items, df_few_shot)

    for item_orig, item_norm in zip(batch_items, normalizados):
        resultados.append({
            'descricao_suja':        item_orig,
            'descricao_normalizada': item_norm,
            'gabarito':              gabarito.get(item_orig, 'N/A'),
        })

    print(f"  Lote {batch_num}/{total_batches} concluído — {min(i + BATCH_SIZE, total_itens)}/{total_itens} itens")

    # Pequena pausa para evitar rate limit (ajuste se necessário)
    if batch_num < total_batches:
        time.sleep(1)

tempo_total = time.time() - tempo_inicio

# Calcular custo estimado
custo_input  = (total_tokens_input  / 1_000_000) * PRECO_INPUT_POR_MILHAO
custo_output = (total_tokens_output / 1_000_000) * PRECO_OUTPUT_POR_MILHAO
custo_total  = custo_input + custo_output

print()
print("=" * 55)
print("RESUMO DA EXECUÇÃO")
print("=" * 55)
print(f"  Itens processados:    {len(resultados)}")
print(f"  Lotes enviados:       {total_batches}")
print(f"  Tempo total:          {tempo_total:.1f}s  ({tempo_total/60:.1f} min)")
print(f"  Tempo médio/lote:     {tempo_total/total_batches:.1f}s")
print()
print(f"  Tokens de entrada:    {total_tokens_input:,}")
print(f"  Tokens de saída:      {total_tokens_output:,}")
print(f"  Tokens totais:        {total_tokens_input + total_tokens_output:,}")
print()
print(f"  Custo estimado:")
print(f"    Input:  USD {custo_input:.6f}")
print(f"    Output: USD {custo_output:.6f}")
print(f"    TOTAL:  USD {custo_total:.6f}  (~R$ {custo_total * 5.7:.4f})")
print("=" * 55)

df_resultados = pd.DataFrame(resultados)
df_resultados.head(10)

Iniciando normalização de 171 itens em 18 lotes de 10...

  Lote 1/18 concluído — 10/171 itens
  Lote 2/18 concluído — 20/171 itens
  Lote 3/18 concluído — 30/171 itens
  Lote 4/18 concluído — 40/171 itens
  Lote 5/18 concluído — 50/171 itens
  Lote 6/18 concluído — 60/171 itens
  Lote 7/18 concluído — 70/171 itens
  Lote 8/18 concluído — 80/171 itens
  Lote 9/18 concluído — 90/171 itens
  Lote 10/18 concluído — 100/171 itens
  Lote 11/18 concluído — 110/171 itens
  Lote 12/18 concluído — 120/171 itens
  Lote 13/18 concluído — 130/171 itens
  Lote 14/18 concluído — 140/171 itens
  Lote 15/18 concluído — 150/171 itens
  Lote 16/18 concluído — 160/171 itens
  Lote 17/18 concluído — 170/171 itens
  Lote 18/18 concluído — 171/171 itens

=======================================================
RESUMO DA EXECUÇÃO
=======================================================
  Itens processados:    171
  Lotes enviados:       18
  Tempo total:          41.8s  (0.7 min)
  Tempo médio/lote:     2.3s

  Tokens de entrada:    20,929
  Tokens de saída:      3,859
  Tokens totais:        24,788

  Custo estimado:
    Input:  USD 0.001570
    Output: USD 0.001158
    TOTAL:  USD 0.002727  (~R$ 0.0155)
=======================================================

,descricao_suja,descricao_normalizada,gabarito
0,COCA COLA 2 LT,Coca-Cola 2 Litros,Coca-Cola 2 Litros
1,COKA COLA 2L,Coca-Cola 2 Litros,Coca-Cola 2 Litros
2,COCA-COLA 2LT,Coca-Cola 2 Litros,Coca-Cola 2 Litros
3,COCACOLA 2 LITROS,Coca-Cola 2 Litros,Coca-Cola 2 Litros
4,CCA COLA 2L,Coca-Cola 2 Litros,Coca-Cola 2 Litros
5,REFRIG COCA 2L,Refrigerante Coca-Cola 2 Litros,Coca-Cola 2 Litros
6,COCA COLA DOIS LITROS,Coca-Cola 2 Litros,Coca-Cola 2 Litros
7,REFRIG CC 2LT,Refrigerante Coca-Cola 2 Litros,Coca-Cola 2 Litros
8,COCA COLA 2000ML,Coca-Cola 2000 ml,Coca-Cola 2 Litros
9,CAD PDO LT50,Cadeado Pado LT-50,Cadeado Pado LT-50MM

---
## 6. Avaliação dos Resultados

Métricas usadas:
- **Exact Match** — % de itens perfeitamente iguais ao gabarito
- **WER (Word Error Rate)** — % de palavras erradas (mesma métrica do PolyNorm)
- **F1-score por tokens** — precisão e recall das palavras previstas vs gabarito

In [ ]:
def calcular_wer(gabarito_str, predicao_str):
    try:
        return wer(gabarito_str.lower(), predicao_str.lower())
    except:
        return 1.0


def calcular_f1_tokens(gabarito_str, predicao_str):
    """Calcula F1 baseado em overlap de tokens (palavras)."""
    tokens_gab  = set(gabarito_str.upper().split())
    tokens_pred = set(predicao_str.upper().split())

    if not tokens_pred or not tokens_gab:
        return 0.0

    tp        = len(tokens_gab & tokens_pred)
    precisao  = tp / len(tokens_pred)
    recall    = tp / len(tokens_gab)

    if precisao + recall == 0:
        return 0.0
    return 2 * (precisao * recall) / (precisao + recall)


df_resultados['wer'] = df_resultados.apply(
    lambda row: calcular_wer(row['gabarito'], row['descricao_normalizada']), axis=1
)
df_resultados['exact_match'] = (
    df_resultados['descricao_normalizada'].str.upper() ==
    df_resultados['gabarito'].str.upper()
)
df_resultados['f1'] = df_resultados.apply(
    lambda row: calcular_f1_tokens(row['gabarito'], row['descricao_normalizada']), axis=1
)

wer_medio         = df_resultados['wer'].mean()
exact_match_rate  = df_resultados['exact_match'].mean()
f1_medio          = df_resultados['f1'].mean()

print("=" * 50)
print("RESULTADOS GERAIS")
print("=" * 50)
print(f"Exact Match:       {exact_match_rate:.2%}  (quanto maior, melhor)")
print(f"F1 médio:          {f1_medio:.2%}  (quanto maior, melhor)")
print(f"WER médio:         {wer_medio:.2%}  (quanto menor, melhor)")
print(f"Total avaliado:    {len(df_resultados)} itens")
print()

==================================================
RESULTADOS GERAIS
==================================================
Exact Match:       91.81%  (quanto maior, melhor)
F1 médio:          96.16%  (quanto maior, melhor)
WER médio:         6.56%  (quanto menor, melhor)
Total avaliado:    171 itens

In [ ]:
# Resultado por produto
# Adiciona produto_id ao df_resultados para agrupar
df_resultados['produto_id'] = df_test['produto_id'].values

resultado_por_produto = df_resultados.groupby('produto_id').agg(
    gabarito       = ('gabarito',              'first'),
    exact_match    = ('exact_match',            'mean'),
    f1_medio       = ('f1',                     'mean'),
    wer_medio      = ('wer',                    'mean'),
    total_itens    = ('wer',                    'count')
).reset_index()

resultado_por_produto = resultado_por_produto.sort_values('f1_medio', ascending=True)
resultado_por_produto['exact_match'] = resultado_por_produto['exact_match'].map('{:.2%}'.format)
resultado_por_produto['f1_medio']    = resultado_por_produto['f1_medio'].map('{:.2%}'.format)
resultado_por_produto['wer_medio']   = resultado_por_produto['wer_medio'].map('{:.2%}'.format)

print("=" * 70)
print("MÉTRICAS POR PRODUTO (ordenado do pior F1 para o melhor)")
print("=" * 70)
print(resultado_por_produto.to_string(index=False))

======================================================================
MÉTRICAS POR PRODUTO (ordenado do pior F1 para o melhor)
======================================================================
 produto_id                                      gabarito exact_match f1_medio wer_medio  total_itens
          1                          Cadeado Pado LT-50MM       0.00%   43.69%   103.70%            9
          0                            Coca-Cola 2 Litros      66.67%   89.42%    14.81%            9
          4                 Leite Integral Italac 1 Litro      88.89%   95.56%     4.44%            9
         15 Fralda Pampers Supersec Tamanho M 30 Unidades      88.89%   98.41%     1.59%            9
          3                   Feijão Carioca Kicaldo 1 Kg     100.00%  100.00%     0.00%            9
          5                     Açúcar Cristal União 1 Kg     100.00%  100.00%     0.00%            9
          6                  Café Tradicional Pilão 500 g     100.00%  100.00%     0.00%            9
          2                    Arroz Branco Tio João 1 Kg     100.00%  100.00%     0.00%            9
          7                   Detergente Limão Ypê 500 ml     100.00%  100.00%     0.00%            9
          8                  Sabão em Pó OMO Lavanda 1 Kg     100.00%  100.00%     0.00%            9
         10         Biscoito Cream Cracker Bauducco 200 g     100.00%  100.00%     0.00%            9
          9           Água Mineral Sem Gás Crystal 500 ml     100.00%  100.00%     0.00%            9
         11                Macarrão Espaguete Adria 500 g     100.00%  100.00%     0.00%            9
         12               Azeite Extra Virgem Galo 500 ml     100.00%  100.00%     0.00%            9
         13     Shampoo Anticaspa Head & Shoulders 200 ml     100.00%  100.00%     0.00%            9
         14               Creme Dental Menta Colgate 90 g     100.00%  100.00%     0.00%            9
         16           Cerveja Skol Puro Malte 269 ml Lata     100.00%  100.00%     0.00%            9
         17                   Pneu 175/70 R13 Bridgestone     100.00%  100.00%     0.00%            9
         18  Óleo de Motor Sintético 5W30 Castrol 1 Litro     100.00%  100.00%     0.00%            9

---
## 7. Análise de Erros

In [ ]:
df_erros = df_resultados[~df_resultados['exact_match']].sort_values('wer', ascending=False)

print(f"Itens com erro: {len(df_erros)} de {len(df_resultados)} ({len(df_erros)/len(df_resultados):.1%})")
print()
print("=" * 70)
print("ERROS (ordenados do pior WER para o melhor)")
print("=" * 70)

for _, row in df_erros.head(20).iterrows():
    print(f"ENTRADA:   {row['descricao_suja']}")
    print(f"RESULTADO: {row['descricao_normalizada']}")
    print(f"GABARITO:  {row['gabarito']}")
    print(f"WER:       {row['wer']:.2%}   F1: {row['f1']:.2%}")
    print("-" * 70)

Itens com erro: 14 de 171 (8.2%)

======================================================================
ERROS (ordenados do pior WER para o melhor)
======================================================================
ENTRADA:   CADEADO PADRAO LT 50MM
RESULTADO: Cadeado Padrão LT 50 mm
GABARITO:  Cadeado Pado LT-50MM
WER:       133.33%   F1: 25.00%
----------------------------------------------------------------------
ENTRADA:   CAD PADR LT-50MM
RESULTADO: Cadeado Padrão LT 50 mm
GABARITO:  Cadeado Pado LT-50MM
WER:       133.33%   F1: 25.00%
----------------------------------------------------------------------
ENTRADA:   CADEADO PADO MOD LT50
RESULTADO: Cadeado Pado Modelo LT 50 mm
GABARITO:  Cadeado Pado LT-50MM
WER:       133.33%   F1: 44.44%
----------------------------------------------------------------------
ENTRADA:   CDO PAD LT 50 MM
RESULTADO: Cadeado Padrão LT 50 mm
GABARITO:  Cadeado Pado LT-50MM
WER:       133.33%   F1: 25.00%
----------------------------------------------------------------------
ENTRADA:   CADEADO PADO LT50MM
RESULTADO: Cadeado Pado LT 50 mm
GABARITO:  Cadeado Pado LT-50MM
WER:       100.00%   F1: 50.00%
----------------------------------------------------------------------
ENTRADA:   CDO PADO LT-50
RESULTADO: Cadeado Pado LT 50 mm
GABARITO:  Cadeado Pado LT-50MM
WER:       100.00%   F1: 50.00%
----------------------------------------------------------------------
ENTRADA:   CADEADO PADO LT - 50 MM
RESULTADO: Cadeado Pado LT 50 mm
GABARITO:  Cadeado Pado LT-50MM
WER:       100.00%   F1: 50.00%
----------------------------------------------------------------------
ENTRADA:   CADEADO PDO 50MM
RESULTADO: Cadeado Pado 50 mm
GABARITO:  Cadeado Pado LT-50MM
WER:       66.67%   F1: 57.14%
----------------------------------------------------------------------
ENTRADA:   COCA COLA 2000ML
RESULTADO: Coca-Cola 2000 ml
GABARITO:  Coca-Cola 2 Litros
WER:       66.67%   F1: 33.33%
----------------------------------------------------------------------
ENTRADA:   LEITE ITALAC INTEG 1000ML
RESULTADO: Leite Integral Italac 1000 ml
GABARITO:  Leite Integral Italac 1 Litro
WER:       40.00%   F1: 60.00%
----------------------------------------------------------------------
ENTRADA:   CAD PDO LT50
RESULTADO: Cadeado Pado LT-50
GABARITO:  Cadeado Pado LT-50MM
WER:       33.33%   F1: 66.67%
----------------------------------------------------------------------
ENTRADA:   REFRIG CC 2LT
RESULTADO: Refrigerante Coca-Cola 2 Litros
GABARITO:  Coca-Cola 2 Litros
WER:       33.33%   F1: 85.71%
----------------------------------------------------------------------
ENTRADA:   REFRIG COCA 2L
RESULTADO: Refrigerante Coca-Cola 2 Litros
GABARITO:  Coca-Cola 2 Litros
WER:       33.33%   F1: 85.71%
----------------------------------------------------------------------
ENTRADA:   FRALDA PAMPERS SUPERSEC MEDIO 30
RESULTADO: Fralda Pampers Supersec Tamanho Médio 30 Unidades
GABARITO:  Fralda Pampers Supersec Tamanho M 30 Unidades
WER:       14.29%   F1: 85.71%
----------------------------------------------------------------------

In [ ]:
df_acertos = df_resultados[df_resultados['exact_match']]

print(f"Acertos perfeitos: {len(df_acertos)} de {len(df_resultados)} ({len(df_acertos)/len(df_resultados):.1%})")
print()
print("=" * 70)
print("ACERTOS PERFEITOS")
print("=" * 70)

for _, row in df_acertos.head(20).iterrows():
    print(f"ENTRADA:   {row['descricao_suja']}")
    print(f"RESULTADO: {row['descricao_normalizada']}")
    print("-" * 70)

Acertos perfeitos: 157 de 171 (91.8%)

======================================================================
ACERTOS PERFEITOS
======================================================================
ENTRADA:   COCA COLA 2 LT
RESULTADO: Coca-Cola 2 Litros
----------------------------------------------------------------------
ENTRADA:   COKA COLA 2L
RESULTADO: Coca-Cola 2 Litros
----------------------------------------------------------------------
ENTRADA:   COCA-COLA 2LT
RESULTADO: Coca-Cola 2 Litros
----------------------------------------------------------------------
ENTRADA:   COCACOLA 2 LITROS
RESULTADO: Coca-Cola 2 Litros
----------------------------------------------------------------------
ENTRADA:   CCA COLA 2L
RESULTADO: Coca-Cola 2 Litros
----------------------------------------------------------------------
ENTRADA:   COCA COLA DOIS LITROS
RESULTADO: Coca-Cola 2 Litros
----------------------------------------------------------------------
ENTRADA:   ARROZ BRANCO TIO JOAO 1KG
RESULTADO: Arroz Branco Tio João 1 Kg
----------------------------------------------------------------------
ENTRADA:   ARZ BCO TIO JOAO 1 KG
RESULTADO: Arroz Branco Tio João 1 Kg
----------------------------------------------------------------------
ENTRADA:   ARROZ TIO JOAO BCO 1KG
RESULTADO: Arroz Branco Tio João 1 Kg
----------------------------------------------------------------------
ENTRADA:   ARR BRANCO TIO JOAO 1KG
RESULTADO: Arroz Branco Tio João 1 Kg
----------------------------------------------------------------------
ENTRADA:   ARRZ TIO JOA BCO 1KG
RESULTADO: Arroz Branco Tio João 1 Kg
----------------------------------------------------------------------
ENTRADA:   ARROZ BCO 1KG TIO JOAO
RESULTADO: Arroz Branco Tio João 1 Kg
----------------------------------------------------------------------
ENTRADA:   ARZ BRCO TIO JOAO 1KG
RESULTADO: Arroz Branco Tio João 1 Kg
----------------------------------------------------------------------
ENTRADA:   ARROZ BCO TIO JO 1KG
RESULTADO: Arroz Branco Tio João 1 Kg
----------------------------------------------------------------------
ENTRADA:   ARR BCO T JOAO 1 KG
RESULTADO: Arroz Branco Tio João 1 Kg
----------------------------------------------------------------------
ENTRADA:   FEIJAO CARIOCA KICALDO 1KG
RESULTADO: Feijão Carioca Kicaldo 1 Kg
----------------------------------------------------------------------
ENTRADA:   FEIJ CAR KICALDO 1 KG
RESULTADO: Feijão Carioca Kicaldo 1 Kg
----------------------------------------------------------------------
ENTRADA:   FJO CARIOCA KICALDO 1KG
RESULTADO: Feijão Carioca Kicaldo 1 Kg
----------------------------------------------------------------------
ENTRADA:   FEIJAO CARICOA KICALDO 1KG
RESULTADO: Feijão Carioca Kicaldo 1 Kg
----------------------------------------------------------------------
ENTRADA:   FEIJ CARIOCA KIC 1KG
RESULTADO: Feijão Carioca Kicaldo 1 Kg
----------------------------------------------------------------------

In [ ]:
# Salvar resultados completos
df_resultados.to_csv('resultados_normalizacao_gemini.csv', index=False)
print("Resultados salvos em: resultados_normalizacao_gemini.csv")
print()
print("Resumo final:")
print(f"  Exact Match: {df_resultados['exact_match'].mean():.2%}")
print(f"  F1 médio:    {df_resultados['f1'].mean():.2%}")
print(f"  WER médio:   {df_resultados['wer'].mean():.2%}")
print(f"  Tempo total: {tempo_total:.1f}s")
print(f"  Custo total: USD {custo_total:.6f}")

Resultados salvos em: resultados_normalizacao_gemini.csv

Resumo final:
  Exact Match: 91.81%
  F1 médio:    96.16%
  WER médio:   6.56%
  Tempo total: 41.8s
  Custo total: USD 0.002727